/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.frame;

import vista.frame.*;
import modelo.ComunicacionREST;
import comun.Usuario;
import java.net.HttpURLConnection;
import java.net.MalformedURLException; 
import java.net.URL;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bárbara Fernández
 */
public class InicioSesion extends javax.swing.JFrame {

    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
      
    private String encriptarClave(String clave){
        String claveHash = "";
        try{
            MessageDigest messageDigest = MessageDigest.getInstance("MD5"); // Inicializa MD5

               try{
                  byte[] bytesClave = clave.getBytes("UTF-8");
                  messageDigest.update(bytesClave);
                  byte[] hash = messageDigest.digest(); // Genera el hash MD5

                  //Pasar los hash a hexadecimal
                  for (int i = 0; i < hash.length; i++)
                  {
                     claveHash += Integer.toHexString((hash[i] >> 4) & 0xf);
                     claveHash += Integer.toHexString(hash[i] & 0xf);
                  }
               }
               catch(Exception e) {
                   e.getStackTrace();
               }

            }   
        catch(Exception e) {
            e.getStackTrace();
        }
        return claveHash;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_ventanaInicio = new javax.swing.JPanel();
        txt_nombreUsuario = new javax.swing.JTextField();
        txt_claveUsuario = new javax.swing.JPasswordField();
        btn_Ingresar = new javax.swing.JButton();
        lbl_tituloInicioSesion = new javax.swing.JLabel();
        pnl_verde = new javax.swing.JPanel();
        pnl_blanco = new javax.swing.JPanel();
        lbl_rif = new javax.swing.JLabel();
        lbl_nit = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ventanaInicio.setBackground(new java.awt.Color(251, 248, 248));
        lbl_ventanaInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 2, true));

        txt_nombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txt_nombreUsuario.setText("Nombre del usuario");
        txt_nombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 166, 72)));
        txt_nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreUsuarioActionPerformed(evt);
            }
        });

        txt_claveUsuario.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        txt_claveUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txt_claveUsuario.setText("jPasswordField1");
        txt_claveUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 158, 55)));
        txt_claveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveUsuarioActionPerformed(evt);
            }
        });

        btn_Ingresar.setBackground(new java.awt.Color(204, 204, 204));
        btn_Ingresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.setBorder(null);
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });

        lbl_tituloInicioSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_tituloInicioSesion.setText("Inicio de Sesión");

        javax.swing.GroupLayout lbl_ventanaInicioLayout = new javax.swing.GroupLayout(lbl_ventanaInicio);
        lbl_ventanaInicio.setLayout(lbl_ventanaInicioLayout);
        lbl_ventanaInicioLayout.setHorizontalGroup(
            lbl_ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ventanaInicioLayout.createSequentialGroup()
                .addGroup(lbl_ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lbl_ventanaInicioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tituloInicioSesion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbl_ventanaInicioLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(lbl_ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txt_claveUsuario))))
                .addGap(50, 50, 50))
            .addGroup(lbl_ventanaInicioLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btn_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbl_ventanaInicioLayout.setVerticalGroup(
            lbl_ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_ventanaInicioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_tituloInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_claveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(lbl_ventanaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 230, 310));

        pnl_verde.setBackground(new java.awt.Color(15, 69, 16));
        pnl_verde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 630, 260));

        pnl_blanco.setBackground(new java.awt.Color(255, 255, 255));

        lbl_rif.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_rif.setText("R.I.F. J-31139418-4");

        lbl_nit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_nit.setText("N.I.T. 032550532 ");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/img/logomini.png"))); // NOI18N

        javax.swing.GroupLayout pnl_blancoLayout = new javax.swing.GroupLayout(pnl_blanco);
        pnl_blanco.setLayout(pnl_blancoLayout);
        pnl_blancoLayout.setHorizontalGroup(
            pnl_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_blancoLayout.createSequentialGroup()
                .addGroup(pnl_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_blancoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pnl_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nit)
                            .addComponent(lbl_rif)))
                    .addGroup(pnl_blancoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lbl_logo)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        pnl_blancoLayout.setVerticalGroup(
            pnl_blancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_blancoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lbl_logo)
                .addGap(18, 18, 18)
                .addComponent(lbl_rif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nit)
                .addGap(38, 38, 38))
        );

        getContentPane().add(pnl_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreUsuarioActionPerformed
       
    }//GEN-LAST:event_txt_nombreUsuarioActionPerformed

    private void txt_claveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveUsuarioActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        
        try {
            
            Usuario usuarioLogin = new Usuario(txt_nombreUsuario.getText(), encriptarClave(txt_claveUsuario.getText()));
            ComunicacionREST com = new ComunicacionREST();
            Usuario validar = com.iniciarSesion(usuarioLogin);
            
            if(validar.getError() == 200)
            {        
                if (validar.getUsuario().equals("jfgp")){
                    AppMenu nuevaVentana = new AppMenu(1);
                    nuevaVentana.setVisible(true);
                    this.setVisible(false);
                }
                if (validar.getUsuario().equals("roxana1208")){
                    AppMenu nuevaVentana = new AppMenu(2);
                    nuevaVentana.setVisible(true);
                    this.setVisible(false);
                }
            }
            else
            {
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_rif;
    private javax.swing.JLabel lbl_tituloInicioSesion;
    private javax.swing.JPanel lbl_ventanaInicio;
    private javax.swing.JPanel pnl_blanco;
    private javax.swing.JPanel pnl_verde;
    private javax.swing.JPasswordField txt_claveUsuario;
    private javax.swing.JTextField txt_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
