/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.grupos;

import comun.Emp_Gru_Est;
import comun.Grupo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.ComunicacionREST;

/**
 *
 * @author Ronald
 */
public class ConsultarGrupos extends javax.swing.JPanel {
    DefaultTableModel model;
    DefaultTableModel model2;
    private Emp_Gru_Est gruestConsultar;
    private ArrayList<Emp_Gru_Est> listaGrupos;

    /**
     * Creates new form ConsultarGrupos
     */
    public ConsultarGrupos() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            ArrayList<Grupo> listaGrupos = comRest.consultarGrupos();
            
            model = (DefaultTableModel) tb_consultarGrupo.getModel();
            model2 = (DefaultTableModel) tb_consultarEstudianteGrupo.getModel();
            
            
            for (Grupo grupo : listaGrupos) {
               model.addRow(new Object[] {grupo.getCodigo(), grupo.getNombre(), grupo.getDescripcion(), grupo.getCapacidad(), grupo.getPeriodo()});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultarGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloGrupos = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        sp_representantes = new javax.swing.JScrollPane();
        tb_consultarEstudianteGrupo = new javax.swing.JTable();
        sp_representantes1 = new javax.swing.JScrollPane();
        tb_consultarGrupo = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloGrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloGrupos.setText("Consultar Grupos");

        pnl_datos.setBackground(new java.awt.Color(204, 204, 204));
        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        tb_consultarEstudianteGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_consultarEstudianteGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula ", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_consultarEstudianteGrupo.setUpdateSelectionOnSort(false);
        sp_representantes.setViewportView(tb_consultarEstudianteGrupo);

        tb_consultarGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_consultarGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Capacidad", "Periodo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_consultarGrupo.setUpdateSelectionOnSort(false);
        tb_consultarGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_consultarGrupoMouseClicked(evt);
            }
        });
        sp_representantes1.setViewportView(tb_consultarGrupo);

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_datosLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(sp_representantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_datosLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(sp_representantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_tituloGrupos)
                .addContainerGap(776, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_tituloGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(590, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_consultarGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_consultarGrupoMouseClicked
        
        model2.setRowCount(0);
        int index = 0;
        String codigo = null;
        try {
            
            index = tb_consultarGrupo.getSelectedRow();
            codigo = model.getValueAt(index, 0).toString();
            
            Grupo _grupo = new Grupo(codigo);
            gruestConsultar = new Emp_Gru_Est(_grupo);
            
            ComunicacionREST comRest = new ComunicacionREST();
            
            listaGrupos = comRest.consultarParametroEstudiantesGrupo(gruestConsultar);
            
            for (Emp_Gru_Est gruest : listaGrupos) {
               model2.addRow(new Object[] {gruest.getEstudiante().getCedulaEscolar(), gruest.getEstudiante().getPrimerNombre(), gruest.getEstudiante().getPrimerApellido()});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultarGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_consultarGrupoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_tituloGrupos;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JScrollPane sp_representantes;
    private javax.swing.JScrollPane sp_representantes1;
    private javax.swing.JTable tb_consultarEstudianteGrupo;
    private javax.swing.JTable tb_consultarGrupo;
    // End of variables declaration//GEN-END:variables
}
