/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.grupos;

import comun.Emp_Gru_Est;
import comun.Grupo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.ComunicacionREST;

/**
 *
 * @author Ronald
 */
public class ConsultarGrupos extends javax.swing.JPanel {
    DefaultTableModel model;
    DefaultTableModel model2;
    private Emp_Gru_Est gruestConsultar;
    private ArrayList<Emp_Gru_Est> listaGrupos;
    private ArrayList<Emp_Gru_Est> listaGruposEmp;

    /**
     * Creates new form ConsultarGrupos
     */
    public ConsultarGrupos() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            ArrayList<Grupo> listaGrupos = comRest.consultarGrupos();
            
            model = (DefaultTableModel) tb_consultarGrupo.getModel();
            model2 = (DefaultTableModel) tb_consultarEstudianteGrupo.getModel();
            
            
            for (Grupo grupo : listaGrupos) {
               model.addRow(new Object[] {grupo.getCodigo(), grupo.getNombre(), grupo.getDescripcion(), grupo.getCapacidad(), grupo.getPeriodo()});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultarGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloGrupos = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        sp_representantes = new javax.swing.JScrollPane();
        tb_consultarEstudianteGrupo = new javax.swing.JTable();
        sp_representantes1 = new javax.swing.JScrollPane();
        tb_consultarGrupo = new javax.swing.JTable();
        lbl_nombreDocente = new javax.swing.JLabel();
        txt_nombreDocente = new javax.swing.JTextField();
        lbl_apellidoDocente = new javax.swing.JLabel();
        txt_apellidoDocente = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloGrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloGrupos.setText("Consultar Grupos");

        pnl_datos.setBackground(new java.awt.Color(204, 204, 204));
        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        tb_consultarEstudianteGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_consultarEstudianteGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula ", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_consultarEstudianteGrupo.setUpdateSelectionOnSort(false);
        sp_representantes.setViewportView(tb_consultarEstudianteGrupo);

        tb_consultarGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_consultarGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Capacidad", "Periodo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_consultarGrupo.setUpdateSelectionOnSort(false);
        tb_consultarGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_consultarGrupoMouseClicked(evt);
            }
        });
        sp_representantes1.setViewportView(tb_consultarGrupo);

        lbl_nombreDocente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_nombreDocente.setText("Nombre Docente:");

        txt_nombreDocente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_nombreDocente.setEnabled(false);

        lbl_apellidoDocente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_apellidoDocente.setText("Apellido Docente:");

        txt_apellidoDocente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_apellidoDocente.setEnabled(false);

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_representantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_nombreDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lbl_apellidoDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_apellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp_representantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreDocente)
                    .addComponent(txt_nombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_apellidoDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tituloGrupos))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_tituloGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_consultarGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_consultarGrupoMouseClicked
        
        model2.setRowCount(0);
        int index = 0;
        String codigo = null;
        try {
            
            index = tb_consultarGrupo.getSelectedRow();
            codigo = model.getValueAt(index, 0).toString();
            
            Grupo _grupo = new Grupo(codigo);
            gruestConsultar = new Emp_Gru_Est(_grupo);
            
            ComunicacionREST comRest = new ComunicacionREST();
            
            listaGrupos = comRest.consultarParametroEstudiantesGrupo(gruestConsultar);
            listaGruposEmp = comRest.consultarParametroEmpleadoGrupo(gruestConsultar);
            
            for (Emp_Gru_Est gruest : listaGrupos) {
               model2.addRow(new Object[] {gruest.getEstudiante().getCedulaEscolar(), gruest.getEstudiante().getPrimerNombre(), gruest.getEstudiante().getPrimerApellido()});
            }
            
            for (Emp_Gru_Est gruest : listaGruposEmp){
                
                if(gruest.getEmpleado().getCargo().equals("Docente")){
                    txt_nombreDocente.setText(gruest.getEmpleado().getPrimerNombre());
                    txt_apellidoDocente.setText(gruest.getEmpleado().getPrimerApellido());
                }
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultarGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_consultarGrupoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_apellidoDocente;
    private javax.swing.JLabel lbl_nombreDocente;
    private javax.swing.JLabel lbl_tituloGrupos;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JScrollPane sp_representantes;
    private javax.swing.JScrollPane sp_representantes1;
    private javax.swing.JTable tb_consultarEstudianteGrupo;
    private javax.swing.JTable tb_consultarGrupo;
    private javax.swing.JTextField txt_apellidoDocente;
    private javax.swing.JTextField txt_nombreDocente;
    // End of variables declaration//GEN-END:variables
}
