/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.estudiantes;

import comun.Estudiante;
import comun.Rep_Est;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.ComunicacionREST;
import modelo.Registry;

/**
 *
 * @author Ronald
 */
public class AsignarRelacion extends javax.swing.JPanel {
    long cedulaEstudiante;
    int cedulaRepresentante;
    /**
     * Creates new form AsignarRelacion
     */
    public AsignarRelacion() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            ArrayList<Estudiante> listaEstudiantes = comRest.consultarEstudiantes();
            for (Estudiante estudiante : listaEstudiantes) {
                cb_listaEstudiantes.addItem(estudiante);
            }
            cb_listaEstudiantes.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        Estudiante estudianteSeleccionado = (Estudiante) cb_listaEstudiantes.getSelectedItem();
                        String cedulaEscolar = Long.toString(estudianteSeleccionado.getCedulaEscolar());
                        txt_CedulaEstudiante.setText(cedulaEscolar);
                        cedulaEstudiante = estudianteSeleccionado.getCedulaEscolar();
                    } catch (Exception ex) {
                        Logger.getLogger(AsignarRelacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
        } catch (Exception ex) {
            Logger.getLogger(AsignarRelacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloEstudiantes = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        txt_CedulaEstudiante = new javax.swing.JTextField();
        lbl_cedulaEstudiante = new javax.swing.JLabel();
        btn_asignar = new javax.swing.JButton();
        cb_listaEstudiantes = new javax.swing.JComboBox();
        lbl_estudiante = new javax.swing.JLabel();
        cb_parentezco = new javax.swing.JComboBox();
        lbl_parentezco = new javax.swing.JLabel();
        txt_CedulaRepresentante = new javax.swing.JTextField();
        lbl_cedulaRepresentante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloEstudiantes.setText("Asignar Relacion Estudiante - Representante");

        pnl_datos.setBackground(new java.awt.Color(204, 204, 204));
        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        txt_CedulaEstudiante.setBackground(new java.awt.Color(240, 240, 240));
        txt_CedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_CedulaEstudiante.setEnabled(false);

        lbl_cedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cedulaEstudiante.setText("CI Estudiante:");

        btn_asignar.setBackground(new java.awt.Color(121, 213, 177));
        btn_asignar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_asignar.setText("Asignar");
        btn_asignar.setActionCommand("Eliminar");
        btn_asignar.setPreferredSize(new java.awt.Dimension(109, 25));
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarActionPerformed(evt);
            }
        });

        cb_listaEstudiantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_estudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_estudiante.setText("Estudiante:");

        cb_parentezco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Madre", "Padre", "Autorizado", "Otro" }));

        lbl_parentezco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_parentezco.setText("Parentezco:");

        txt_CedulaRepresentante.setBackground(new java.awt.Color(240, 240, 240));
        txt_CedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_cedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cedulaRepresentante.setText("CI Representante:");

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cedulaEstudiante)
                            .addComponent(lbl_estudiante)
                            .addComponent(lbl_parentezco)
                            .addComponent(lbl_cedulaRepresentante))
                        .addGap(35, 35, 35)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_listaEstudiantes, 0, 192, Short.MAX_VALUE)
                            .addComponent(cb_parentezco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_CedulaEstudiante)
                            .addComponent(txt_CedulaRepresentante)))
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(btn_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 364, Short.MAX_VALUE))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estudiante)
                    .addComponent(cb_listaEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CedulaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedulaEstudiante))
                .addGap(33, 33, 33)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CedulaRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedulaRepresentante))
                .addGap(33, 33, 33)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_parentezco)
                    .addComponent(cb_parentezco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btn_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tituloEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_tituloEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarActionPerformed
        if((!txt_CedulaEstudiante.getText().equals("")) && (!txt_CedulaRepresentante.getText().equals("")) && (cb_parentezco.getSelectedItem() != null)) {
            try {
                
                cedulaRepresentante = Integer.parseInt(txt_CedulaRepresentante.getText());
                Rep_Est repestRegistar = new Rep_Est(cedulaRepresentante, cedulaEstudiante, (String) cb_parentezco.getSelectedItem());
                ComunicacionREST comRest = new ComunicacionREST();
                Rep_Est repestRegistrado = comRest.registrarRepEst(repestRegistar);
                
                if (repestRegistrado.getError() == Registry.RESULTADO_CODIGO_BIEN){
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "Se realizo exitosamente la asignacion", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "No se pudo realizar la asignacion, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(BorrarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "No debe dejar los campos vacios, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_btn_asignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asignar;
    private javax.swing.JComboBox cb_listaEstudiantes;
    private javax.swing.JComboBox cb_parentezco;
    private javax.swing.JLabel lbl_cedulaEstudiante;
    private javax.swing.JLabel lbl_cedulaRepresentante;
    private javax.swing.JLabel lbl_estudiante;
    private javax.swing.JLabel lbl_parentezco;
    private javax.swing.JLabel lbl_tituloEstudiantes;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JTextField txt_CedulaEstudiante;
    private javax.swing.JTextField txt_CedulaRepresentante;
    // End of variables declaration//GEN-END:variables
}
