/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.estudiantes;

import comun.Rep_Est;
import comun.Representante;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.ComunicacionREST;
import modelo.Registry;

/**
 *
 * @author Ronald
 */
public class ConsultarRelacion extends javax.swing.JPanel {
    private Rep_Est repestConsultar;
    private Representante representanteConsultar;
    int cedulaRepresentante;
    DefaultTableModel model;
    
    
    public ConsultarRelacion() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
             ArrayList<Rep_Est> listaRepEst = comRest.consultarRepEst();
             
             model = (DefaultTableModel) tb_consultarRepEst.getModel();
             
             for (Rep_Est repest : listaRepEst) {
               model.addRow(new Object[] {repest.getCedula(), repest.getPrimerNombre_Rep(), repest.getPrimerApellido_Rep(), repest.getCedulaEscolar(), repest.getPrimerNombre_Est(), repest.getPrimerApellido_Est(), repest.getParentezco()});
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultarRelacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloConsultar = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        sp_representantes = new javax.swing.JScrollPane();
        tb_consultarRepEst = new javax.swing.JTable();
        lbl_telfCasa = new javax.swing.JLabel();
        lbl_fotoEst = new javax.swing.JLabel();
        lbl_fotoEstudiante = new javax.swing.JLabel();
        txt_telfCasa = new javax.swing.JTextField();
        lbl_telfCasa1 = new javax.swing.JLabel();
        txt_telefonoMovil = new javax.swing.JTextField();
        lbl_fotoRepresentante = new javax.swing.JLabel();
        lbl_fotoRep = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloConsultar.setText("Consultar Relacion Estudiante - Representante");

        pnl_datos.setBackground(new java.awt.Color(204, 204, 204));
        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        tb_consultarRepEst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_consultarRepEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula Representante", "Nombre", "Apellido", "Cedula Estudiante", "Nombre", "Apellido", "Parentezco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_consultarRepEst.setUpdateSelectionOnSort(false);
        tb_consultarRepEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_consultarRepEstMouseClicked(evt);
            }
        });
        sp_representantes.setViewportView(tb_consultarRepEst);

        lbl_telfCasa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_telfCasa.setText("Telefono Casa:");

        lbl_fotoEst.setBackground(new java.awt.Color(255, 255, 255));
        lbl_fotoEst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_fotoEst.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fotoEst.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_fotoEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_fotoEstudiante.setText("Foto del Estudiante:");

        txt_telfCasa.setEditable(false);
        txt_telfCasa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_telfCasa.setEnabled(false);

        lbl_telfCasa1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_telfCasa1.setText("Telefono Movil:");

        txt_telefonoMovil.setEditable(false);
        txt_telefonoMovil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_telefonoMovil.setEnabled(false);

        lbl_fotoRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_fotoRepresentante.setText("Foto del Representante:");

        lbl_fotoRep.setBackground(new java.awt.Color(255, 255, 255));
        lbl_fotoRep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_fotoRep.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fotoRep.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                                .addComponent(lbl_telfCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_telfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_fotoEstudiante))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(lbl_fotoRepresentante))
                            .addGroup(pnl_datosLayout.createSequentialGroup()
                                .addComponent(lbl_telfCasa1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_telefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(314, 314, 314)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fotoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fotoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                        .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sp_representantes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fotoEstudiante)
                            .addComponent(lbl_telfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telfCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_fotoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_fotoRepresentante)
                        .addGap(80, 80, 80))
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_fotoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbl_tituloConsultar)
                .addContainerGap(571, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_tituloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_consultarRepEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_consultarRepEstMouseClicked
        int index = 0;
        
        try {
            index = tb_consultarRepEst.getSelectedRow();

            String cedula = model.getValueAt(index, 0).toString();
            cedulaRepresentante = Integer.parseInt(cedula);

            ComunicacionREST comRest = new ComunicacionREST();

            Representante _representante = new Representante(cedulaRepresentante);
            representanteConsultar = comRest.consultarRepresentanteDetalle(_representante);

            if (representanteConsultar.getError() == Registry.RESULTADO_CODIGO_BIEN){

                txt_telfCasa.setText(representanteConsultar.getTelefonoCasa());
                txt_telefonoMovil.setText(representanteConsultar.getTelefonoMovil());
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ConsultarEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_consultarRepEstMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_fotoEst;
    private javax.swing.JLabel lbl_fotoEstudiante;
    private javax.swing.JLabel lbl_fotoRep;
    private javax.swing.JLabel lbl_fotoRepresentante;
    private javax.swing.JLabel lbl_telfCasa;
    private javax.swing.JLabel lbl_telfCasa1;
    private javax.swing.JLabel lbl_tituloConsultar;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JScrollPane sp_representantes;
    private javax.swing.JTable tb_consultarRepEst;
    private javax.swing.JTextField txt_telefonoMovil;
    private javax.swing.JTextField txt_telfCasa;
    // End of variables declaration//GEN-END:variables
}
