/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.estudiantes;

import comun.Estudiante;
import comun.Rep_Est;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.ComunicacionREST;
import modelo.Registry;

/**
 *
 * @author Ronald
 */
public class EliminarRelacion extends javax.swing.JPanel {
    long cedulaEstudiante;
    int cedulaRepresentante;
    /**
     * Creates new form EliminarRelacion
     */
    public EliminarRelacion() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            ArrayList<Estudiante> listaEstudiantes = comRest.consultarEstudiantes();
            for (Estudiante estudiante : listaEstudiantes) {
                cb_listaEstudiantes.addItem(estudiante);
            }
            cb_listaEstudiantes.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        Estudiante estudianteSeleccionado = (Estudiante) cb_listaEstudiantes.getSelectedItem();
                        String cedulaEscolar = Long.toString(estudianteSeleccionado.getCedulaEscolar());
                        txt_cedulaEstudiante.setText(cedulaEscolar);
                        cedulaEstudiante = estudianteSeleccionado.getCedulaEscolar();
                    } catch (Exception ex) {
                        Logger.getLogger(AsignarRelacion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(EliminarRelacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloEstudiantes = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        txt_cedulaEstudiante = new javax.swing.JTextField();
        lbl_cedulaEstudiante = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        cb_listaEstudiantes = new javax.swing.JComboBox();
        lbl_estudiante = new javax.swing.JLabel();
        txt_cedulaRepresentante = new javax.swing.JTextField();
        lbl_cedulaRepresentante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloEstudiantes.setText("Borrar Relacion Estudiante - Representante");

        pnl_datos.setBackground(new java.awt.Color(204, 204, 204));
        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        txt_cedulaEstudiante.setBackground(new java.awt.Color(240, 240, 240));
        txt_cedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cedulaEstudiante.setEnabled(false);

        lbl_cedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cedulaEstudiante.setText("Cédula Escolar Estudiante:");

        btn_borrar.setBackground(new java.awt.Color(121, 213, 177));
        btn_borrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_borrar.setText("Borrar");
        btn_borrar.setActionCommand("Eliminar");
        btn_borrar.setPreferredSize(new java.awt.Dimension(109, 25));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        cb_listaEstudiantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_estudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_estudiante.setText("Estudiante:");

        txt_cedulaRepresentante.setBackground(new java.awt.Color(240, 240, 240));
        txt_cedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_cedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_cedulaRepresentante.setText("Cédula de Identidad del Representante:");

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cedulaEstudiante)
                            .addComponent(lbl_estudiante)
                            .addComponent(lbl_cedulaRepresentante))
                        .addGap(35, 35, 35)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_listaEstudiantes, 0, 192, Short.MAX_VALUE)
                            .addComponent(txt_cedulaEstudiante)
                            .addComponent(txt_cedulaRepresentante)))
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 353, Short.MAX_VALUE))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_listaEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_estudiante))
                .addGap(35, 35, 35)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedulaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedulaEstudiante))
                .addGap(35, 35, 35)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedulaRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedulaRepresentante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tituloEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_tituloEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        if((!txt_cedulaEstudiante.getText().equals("")) && (!txt_cedulaRepresentante.getText().equals(""))) {
            try {

                cedulaRepresentante = Integer.parseInt(txt_cedulaRepresentante.getText());
                Rep_Est repestBorrar = new Rep_Est(cedulaRepresentante, cedulaEstudiante);
                ComunicacionREST comRest = new ComunicacionREST();
                Rep_Est repestBorrado = comRest.borrarRepEst(repestBorrar);

                if (repestBorrado.getError() == Registry.RESULTADO_CODIGO_BIEN){
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "Se borro exitosamente la relacion", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "No se pudo borrar la relacion, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(BorrarEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "No debe dejar los campos vacios, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JComboBox cb_listaEstudiantes;
    private javax.swing.JLabel lbl_cedulaEstudiante;
    private javax.swing.JLabel lbl_cedulaRepresentante;
    private javax.swing.JLabel lbl_estudiante;
    private javax.swing.JLabel lbl_tituloEstudiantes;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JTextField txt_cedulaEstudiante;
    private javax.swing.JTextField txt_cedulaRepresentante;
    // End of variables declaration//GEN-END:variables
}
