/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.representantes;

import comun.Estudiante;
import comun.Mensualidad_Representante;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelo.ComunicacionREST;
import modelo.Registry;

/**
 *
 * @author Ronald
 */
public class RegistrarMensualidad extends javax.swing.JPanel {
    
    Long CedulaEscolar;
    String ciEstudiante;
    String codigoMensualidad;
    /**
     * Creates new form RegistrarMensualidad
     */
    public RegistrarMensualidad() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            ArrayList<Estudiante> listaEstudiantes = comRest.consultarEstudiantes();
            for (Estudiante estudiante : listaEstudiantes) {
                cb_estudiante.addItem(estudiante);
            }
            cb_estudiante.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        Estudiante estudianteSeleccionado = (Estudiante) cb_estudiante.getSelectedItem();
                        String cedulaEscolar = Long.toString(estudianteSeleccionado.getCedulaEscolar());
                        txt_cedulaEstudiante.setText(cedulaEscolar);
                        CedulaEscolar = estudianteSeleccionado.getCedulaEscolar();
                    } catch (Exception ex) {
                        Logger.getLogger(RegistrarMensualidad.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            
        } catch (Exception ex) {
            Logger.getLogger(RegistrarMensualidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void keyTypedSoloNumeros(java.awt.event.KeyEvent evt, JTextField campoEvaluar, int tamanoMax){
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE) || (campoEvaluar.getText().length() == tamanoMax)) {
            evt.consume();
        }
    }

    
    public void keyTypedSoloLetras(java.awt.event.KeyEvent evt, JTextField campoEvaluar, int tamanoMax){
        char vChar = evt.getKeyChar();
        
        if ((!(Character.isAlphabetic(vChar)) && (vChar != ' ')) || (campoEvaluar.getText().length() == tamanoMax)) {
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tituloRegistroMensualidad = new javax.swing.JLabel();
        pnl_datos = new javax.swing.JPanel();
        lbl_Monto = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        lbl_fechaNac = new javax.swing.JLabel();
        dc_fechaPago = new datechooser.beans.DateChooserCombo();
        btn_limpiar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        lbl_cedulaRepresentante = new javax.swing.JLabel();
        txt_cedulaRepresentante = new javax.swing.JTextField();
        lbl_banco = new javax.swing.JLabel();
        cb_banco = new javax.swing.JComboBox();
        lbl_numeroTransferencia = new javax.swing.JLabel();
        txt_codigoTransferencia = new javax.swing.JTextField();
        txt_datosPago = new javax.swing.JTextField();
        lbl_datosPago = new javax.swing.JLabel();
        lbl_cedulaEstudiante = new javax.swing.JLabel();
        cb_estudiante = new javax.swing.JComboBox();
        lbl_cedulaEstudiante1 = new javax.swing.JLabel();
        txt_cedulaEstudiante = new javax.swing.JTextField();

        lbl_tituloRegistroMensualidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloRegistroMensualidad.setText("Registro de Mensualidad");

        pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        lbl_Monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Monto.setText("Monto:");

        txt_monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montoKeyTyped(evt);
            }
        });

        lbl_fechaNac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_fechaNac.setText("Fecha de Pago: ");

        dc_fechaPago.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dc_fechaPago.setCalendarBackground(new java.awt.Color(255, 255, 255));
    dc_fechaPago.setCalendarPreferredSize(new java.awt.Dimension(400, 250));
    dc_fechaPago.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
    dc_fechaPago.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 8));

    btn_limpiar.setBackground(new java.awt.Color(153, 0, 0));
    btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
    btn_limpiar.setText("Limpiar");
    btn_limpiar.setPreferredSize(new java.awt.Dimension(109, 25));
    btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_limpiarActionPerformed(evt);
        }
    });

    btn_registrar.setBackground(new java.awt.Color(0, 153, 102));
    btn_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
    btn_registrar.setText("Registrar");
    btn_registrar.setPreferredSize(new java.awt.Dimension(109, 25));
    btn_registrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_registrarActionPerformed(evt);
        }
    });

    lbl_cedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_cedulaRepresentante.setText("Cédula del Representante:");

    txt_cedulaRepresentante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    txt_cedulaRepresentante.setToolTipText("");
    txt_cedulaRepresentante.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txt_cedulaRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_cedulaRepresentanteKeyTyped(evt);
        }
    });

    lbl_banco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_banco.setText("Banco:");

    cb_banco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    cb_banco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100% Banco", "BBVA Banco Provincial", "Bancamiga", "Bancaribe", "Banco Activo", "Banco Agricola de Venezuela", "Banco Bicentenario del Pueblo", "Banco Caroni", "Banco del Tesoro", "Banco de Venezuela", "Banco Exterior", "Banco Mercantil", "Banco Plaza", "Banco Sofitasa", "Banco Venezolano de Credito", "Banesco", "Banfanb", "Banplus", "BFC Banco Fondo Comun", "BNC Banco Nacional de Credito", "BOD Banco Occidental de Descuento", "CitiBank", "DELSUR", "Mi Banco" }));

    lbl_numeroTransferencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_numeroTransferencia.setText("Numero Transferencia:");

    txt_codigoTransferencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    txt_codigoTransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_codigoTransferenciaKeyTyped(evt);
        }
    });

    txt_datosPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    txt_datosPago.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_datosPagoKeyTyped(evt);
        }
    });

    lbl_datosPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_datosPago.setText("Datos del Pago: ");

    lbl_cedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_cedulaEstudiante.setText("Lista de Estudiantes:");

    cb_estudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

    lbl_cedulaEstudiante1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lbl_cedulaEstudiante1.setText("Cedula del Estudiante:");

    txt_cedulaEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    txt_cedulaEstudiante.setToolTipText("");
    txt_cedulaEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    txt_cedulaEstudiante.setEnabled(false);
    txt_cedulaEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txt_cedulaEstudianteKeyTyped(evt);
        }
    });

    javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
    pnl_datos.setLayout(pnl_datosLayout);
    pnl_datosLayout.setHorizontalGroup(
        pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_datosLayout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_Monto)
                .addComponent(lbl_fechaNac)
                .addComponent(lbl_banco)
                .addComponent(lbl_numeroTransferencia)
                .addComponent(lbl_datosPago))
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_datosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_cedulaRepresentante)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txt_cedulaRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_datosLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnl_datosLayout.createSequentialGroup()
                            .addComponent(txt_datosPago, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_cedulaEstudiante1))
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dc_fechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_datosLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_datosLayout.createSequentialGroup()
                                .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(lbl_cedulaEstudiante))
                            .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                    .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cb_estudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cedulaEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(33, 33, 33))
    );
    pnl_datosLayout.setVerticalGroup(
        pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnl_datosLayout.createSequentialGroup()
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_datosLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnl_datosLayout.createSequentialGroup()
                            .addComponent(lbl_numeroTransferencia)
                            .addGap(17, 17, 17))
                        .addGroup(pnl_datosLayout.createSequentialGroup()
                            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_cedulaRepresentante)
                                .addComponent(txt_cedulaRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txt_codigoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_Monto))
            .addGap(18, 18, 18)
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_banco)
                .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_cedulaEstudiante)
                .addComponent(cb_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(dc_fechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(lbl_fechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_datosPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_datosPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cedulaEstudiante1)
                .addComponent(txt_cedulaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
            .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(38, 38, 38))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_tituloRegistroMensualidad))
            .addContainerGap(67, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addComponent(lbl_tituloRegistroMensualidad)
            .addGap(18, 18, 18)
            .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(43, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyTyped
        keyTypedSoloNumeros(evt, txt_monto, 30);
    }//GEN-LAST:event_txt_montoKeyTyped

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_cedulaRepresentante.setText("");
        txt_monto.setText("");
        txt_datosPago.setText("");
        cb_estudiante.setSelectedIndex(0);
        txt_cedulaEstudiante.setText("");
        txt_codigoTransferencia.setText("");
        dc_fechaPago.setCurrent(null);
        cb_banco.setSelectedItem(null);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        
        if ((!txt_codigoTransferencia.getText().equals("")) && (!txt_monto.getText().equals("")) && (!txt_datosPago.getText().equals(""))
            && (!txt_cedulaRepresentante.getText().equals("")) &&(!dc_fechaPago.getText().equals("")) && (cb_banco.getSelectedItem() != null) ){
            
            try {
                ciEstudiante = String.valueOf(CedulaEscolar);
                codigoMensualidad = txt_codigoTransferencia.getText() + ciEstudiante;
            
                SimpleDateFormat parseFecha = new SimpleDateFormat("dd/MM/yy");
                Date fechaPago = parseFecha.parse(dc_fechaPago.getText());
                Calendar calNac = Calendar.getInstance();
                calNac.setTime(fechaPago);
                
                Mensualidad_Representante mensualidadRegistrar = new Mensualidad_Representante(codigoMensualidad, fechaPago, txt_datosPago.getText(),
                                                                Integer.parseInt(txt_monto.getText()), (String) cb_banco.getSelectedItem(), txt_codigoTransferencia.getText(),
                                                                Integer.parseInt(txt_cedulaRepresentante.getText()), Long.parseLong(txt_cedulaEstudiante.getText()));
                ComunicacionREST comRest = new ComunicacionREST();
                Mensualidad_Representante mensualidadRegistrado = comRest.registrarMensualidad(mensualidadRegistrar);
                if ((mensualidadRegistrado.getError() == Registry.RESULTADO_CODIGO_RECURSO_CREADO)){
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "Se registro exitosamente el pago", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "No se ha podido registrar el pago, intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (Exception ex) {
                Logger.getLogger(RegistrarMensualidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else{
        final JPanel panel = new JPanel();
        JOptionPane.showMessageDialog(panel, "No se ha podido registrar el pago, revise los campos", "Error", JOptionPane.ERROR_MESSAGE);
    } 
        
       
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_cedulaRepresentanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaRepresentanteKeyTyped
        keyTypedSoloNumeros(evt, txt_cedulaRepresentante, 8);
    }//GEN-LAST:event_txt_cedulaRepresentanteKeyTyped

    private void txt_codigoTransferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoTransferenciaKeyTyped
        keyTypedSoloNumeros(evt, txt_codigoTransferencia, 30);
    }//GEN-LAST:event_txt_codigoTransferenciaKeyTyped

    private void txt_datosPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_datosPagoKeyTyped
        keyTypedSoloLetras(evt, txt_datosPago, 100);
    }//GEN-LAST:event_txt_datosPagoKeyTyped

    private void txt_cedulaEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaEstudianteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaEstudianteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JComboBox cb_banco;
    private javax.swing.JComboBox cb_estudiante;
    private datechooser.beans.DateChooserCombo dc_fechaPago;
    private javax.swing.JLabel lbl_Monto;
    private javax.swing.JLabel lbl_banco;
    private javax.swing.JLabel lbl_cedulaEstudiante;
    private javax.swing.JLabel lbl_cedulaEstudiante1;
    private javax.swing.JLabel lbl_cedulaRepresentante;
    private javax.swing.JLabel lbl_datosPago;
    private javax.swing.JLabel lbl_fechaNac;
    private javax.swing.JLabel lbl_numeroTransferencia;
    private javax.swing.JLabel lbl_tituloRegistroMensualidad;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JTextField txt_cedulaEstudiante;
    private javax.swing.JTextField txt_cedulaRepresentante;
    private javax.swing.JTextField txt_codigoTransferencia;
    private javax.swing.JTextField txt_datosPago;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables
}
