/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel.empleados;

import comun.Empleado;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.ComunicacionREST;

/**
 *
 * @author LuisAlejandro
 */
public class ActualizarPrestamos extends javax.swing.JPanel {
     private Empleado empleadoSeleccionado;
    
     
     
    public ActualizarPrestamos() {
        try {
            initComponents();
            ComunicacionREST comRest = new ComunicacionREST();
            
            ArrayList<Empleado> listaEmpleados = comRest.consultarEmpleados();
            
            for (Empleado empleado : listaEmpleados) {
                    cb_listaEmpleados.addItem(empleado);
                }
            
        } catch (Exception ex) {
            Logger.getLogger(ActualizarPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_datos = new javax.swing.JPanel();
        sp_empleados = new javax.swing.JScrollPane();
        tb_historicoPrestamos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        cb_listaEmpleados = new javax.swing.JComboBox();
        lbl_empleadoPrestamo = new javax.swing.JLabel();
        txt_montoActual = new javax.swing.JTextField();
        lbl_prestamoActual = new javax.swing.JLabel();
        lbl_bsS = new javax.swing.JLabel();
        txt_montoNuevo = new javax.swing.JTextField();
        lbl_montoNuevo = new javax.swing.JLabel();
        btn_restar = new javax.swing.JButton();
        btn_sumar = new javax.swing.JButton();
        lbl_tituloPrestamos = new javax.swing.JLabel();

        pnl_datos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnl_datos.setPreferredSize(new java.awt.Dimension(840, 520));

        tb_historicoPrestamos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_historicoPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha ", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_historicoPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_historicoPrestamosMouseClicked(evt);
            }
        });
        sp_empleados.setViewportView(tb_historicoPrestamos);

        cb_listaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_empleadoPrestamo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_empleadoPrestamo.setText("Empleado a asignarle préstamo:");

        txt_montoActual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_montoActual.setEnabled(false);
        txt_montoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montoActualKeyTyped(evt);
            }
        });

        lbl_prestamoActual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_prestamoActual.setText("Préstamo Actual:");

        lbl_bsS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_bsS.setText("Bs. S");

        txt_montoNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_montoNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montoNuevoKeyTyped(evt);
            }
        });

        lbl_montoNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_montoNuevo.setText("Monto para actualizar:");

        btn_restar.setBackground(new java.awt.Color(153, 0, 0));
        btn_restar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_restar.setForeground(new java.awt.Color(255, 255, 255));
        btn_restar.setText("Restar");
        btn_restar.setPreferredSize(new java.awt.Dimension(109, 25));
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });

        btn_sumar.setBackground(new java.awt.Color(0, 153, 102));
        btn_sumar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sumar.setForeground(new java.awt.Color(255, 255, 255));
        btn_sumar.setText("Sumar");
        btn_sumar.setPreferredSize(new java.awt.Dimension(109, 25));
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_datosLayout = new javax.swing.GroupLayout(pnl_datos);
        pnl_datos.setLayout(pnl_datosLayout);
        pnl_datosLayout.setHorizontalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_empleadoPrestamo)
                            .addComponent(lbl_prestamoActual)
                            .addComponent(lbl_montoNuevo))
                        .addGap(27, 27, 27)
                        .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_listaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_datosLayout.createSequentialGroup()
                                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_montoNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_montoActual, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_bsS))))
                    .addGroup(pnl_datosLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(btn_restar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(sp_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnl_datosLayout.setVerticalGroup(
            pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(sp_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 55, Short.MAX_VALUE))
            .addGroup(pnl_datosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_listaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_empleadoPrestamo))
                .addGap(45, 45, 45)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_bsS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_montoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_prestamoActual)))
                .addGap(45, 45, 45)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_montoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_montoNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_restar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        lbl_tituloPrestamos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tituloPrestamos.setText("Actualizar Préstamos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tituloPrestamos)
                    .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_tituloPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_historicoPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_historicoPrestamosMouseClicked
        int index = tb_historicoPrestamos.getSelectedRow();

        /*String cedula = model.getValueAt(index, 0).toString();
        try{
            int cedulaEmpleado = Integer.parseInt(cedula);
            ComunicacionREST comRest = new ComunicacionREST();
            Empleado _empleado = new Empleado(cedulaEmpleado);

            empleadoConsultar = comRest.consultarEmpleadoDetalle(_empleado);

            if (empleadoConsultar.getError() == Registry.RESULTADO_CODIGO_BIEN){

                String sueldomen = String.valueOf(empleadoConsultar.getSueldoMensual());
                txt_telefonoCasa.setText(empleadoConsultar.getTelefonoCasa());
                txt_telefonoMovil.setText(empleadoConsultar.getTelefonoMovil());
                txt_sueldoMensual.setText(sueldomen);

                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");

                //to convert Date to String, use format method of SimpleDateFormat class.
                String nacimiento = dateFormat.format(empleadoConsultar.getFechaNac());
                String ingreso = dateFormat.format(empleadoConsultar.getFechaIngreso());

                txt_fechaIngreso.setText(ingreso);
                txt_fechaNac.setText(nacimiento);
                txt_tareasDirigidas.setText(empleadoConsultar.getTareasDirigidas());
                txt_cargo.setText(empleadoConsultar.getCargo());
                txt_banco.setText(empleadoConsultar.getBanco());
                txt_estado.setText(empleadoConsultar.getEstado());
                txt_municipio.setText(empleadoConsultar.getMunicipio());
                txt_parroquia.setText(empleadoConsultar.getParroquia());
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_tb_historicoPrestamosMouseClicked

    private void txt_montoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoActualKeyTyped
        //keyTypedSoloLetras(evt, txt_montoActual, 30);
    }//GEN-LAST:event_txt_montoActualKeyTyped

    private void txt_montoNuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoNuevoKeyTyped
        //keyTypedSoloLetras(evt, txt_montoNuevo, 30);
    }//GEN-LAST:event_txt_montoNuevoKeyTyped

    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        
    }//GEN-LAST:event_btn_restarActionPerformed

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        
    }//GEN-LAST:event_btn_sumarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JComboBox cb_listaEmpleados;
    private javax.swing.JLabel lbl_bsS;
    private javax.swing.JLabel lbl_empleadoPrestamo;
    private javax.swing.JLabel lbl_montoNuevo;
    private javax.swing.JLabel lbl_prestamoActual;
    private javax.swing.JLabel lbl_tituloPrestamos;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JScrollPane sp_empleados;
    private javax.swing.JTable tb_historicoPrestamos;
    private javax.swing.JTextField txt_montoActual;
    private javax.swing.JTextField txt_montoNuevo;
    // End of variables declaration//GEN-END:variables
}
