ALTER TABLE LUGAR
  ADD CONSTRAINT FK_LUGAR
  FOREIGN KEY (FK_LUGAR) 
  REFERENCES LUGAR (CODIGO)
  ON DELETE CASCADE;

ALTER TABLE REPRESENTANTE
  ADD CONSTRAINT FK_REPRESENTANTE
  FOREIGN KEY (FK_LUGAR) 
  REFERENCES LUGAR (CODIGO)
  ON DELETE CASCADE;

ALTER TABLE EMPLEADO
  ADD CONSTRAINT FK_EMPLEADO
  FOREIGN KEY (FK_LUGAR) 
  REFERENCES LUGAR (CODIGO)
  ON DELETE CASCADE;

ALTER TABLE REP_EST
  ADD CONSTRAINT FK_CEDULA
  FOREIGN KEY (FK_CEDULA) 
  REFERENCES REPRESENTANTE (CEDULA)
  ON DELETE CASCADE;

ALTER TABLE REP_EST
  ADD CONSTRAINT FK_CEDULAESCOLAR
  FOREIGN KEY (FK_CEDULAESCOLAR) 
  REFERENCES ESTUDIANTE (CEDULAESCOLAR)
  ON DELETE CASCADE;

ALTER TABLE EMP_GRU_EST
  ADD CONSTRAINT FK_CEDULA
  FOREIGN KEY (FK_CEDULA) 
  REFERENCES REPRESENTANTE (CEDULA)
  ON DELETE CASCADE;
	
ALTER TABLE EMP_GRU_EST
  ADD CONSTRAINT FK_CEDULAESCOLAR
  FOREIGN KEY (FK_CEDULAESCOLAR) 
  REFERENCES ESTUDIANTE (CEDULAESCOLAR)
  ON DELETE CASCADE;

ALTER TABLE EMP_GRU_EST
  ADD CONSTRAINT FK_GRUPO
  FOREIGN KEY (FK_GRUPO) 
  REFERENCES GRUPO (CODIGO)
  ON DELETE CASCADE;

ALTER TABLE COMPROBANTE_PAGO
  ADD CONSTRAINT FK_EMPLEADO
  FOREIGN KEY (FK_EMPLEADO) 
  REFERENCES EMPLEADO (CEDULA)
  ON DELETE CASCADE;
