CREATE USER JoseFelixGonzalez PASSWORD 'josefelix2110';
ALTER ROLE JoseFelixGonzalez WITH SUPERUSER;
CREATE DATABASE HenriPittier WITH OWNER JoseFelixGonzalez;

CREATE TABLE LUGAR(
	CODIGO 					SERIAL,
	TIPO 					VARCHAR(50) NOT NULL,
	NOMBRE 					VARCHAR(80) NOT NULL,
	FK_LUGAR				INTEGER,
	CONSTRAINT PK_LUGAR PRIMARY KEY (CODIGO)
);

CREATE TABLE REPRESENTANTE(
	CEDULA 					INTEGER,
	PRIMERNOMBRE			VARCHAR(30) NOT NULL,
	SEGUNDONOMBRE			VARCHAR(30),
	PRIMERAPELLIDO			VARCHAR(30) NOT NULL,
	SEGUNDOAPELLIDO 		VARCHAR(30),
	FECHANAC				DATE,
	TELEFONOCASA			VARCHAR(11),
	TELEFONOMOVIL			VARCHAR(11),
	TIPO					VARCHAR(17) NOT NULL,
	FOTO					VARCHAR(100) NOT NULL,
	FK_LUGAR 				INTEGER,
	CONSTRAINT CH_TIPO CHECK (TIPO in('Autorizado','Representante I', 'Representante II')),
	CONSTRAINT PK_REPRESENTANTE PRIMARY KEY(CEDULA)	
);

CREATE TABLE EMPLEADO(
	CEDULA 					INTEGER,
	PRIMERNOMBRE 			VARCHAR(30) NOT NULL,
	SEGUNDONOMBRE			VARCHAR (30),
	PRIMERAPELLIDO 			VARCHAR(30) NOT NULL,
	SEGUNDOAPELLIDO			VARCHAR(30),
	BANCO 					VARCHAR(30) NOT NULL,
	SUELDOMENSUAL 			INTEGER NOT NULL,
	FECHAINGRESO 			DATE NOT NULL,
	FECHANAC 				DATE NOT NULL,
	TELEFONOCASA 			VARCHAR(11),
	TELEFONOMOVIL 			VARCHAR(11),
	CARGO 					VARCHAR(30) NOT NULL,
	FOTO 					VARCHAR(100) NOT NULL,
	NOMBREUSUARIO			VARCHAR(50),
	CONTRASENA				VARCHAR(80),
	FK_LUGAR 				INTEGER NOT NULL,
	CONSTRAINT CH_CARGO CHECK (CARGO in('Docente','Auxiliar', 'Director/a', 'Secretario/a', 'Obrero/a','Coordinador/a', 'Administrador/a')),
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA)
);

CREATE TABLE ESTUDIANTE(
	CEDULAESCOLAR 			BIGINT,
	PRIMERNOMBRE			VARCHAR(30) NOT NULL,
	SEGUNDONOMBRE			VARCHAR(30),
	PRIMERAPELLIDO			VARCHAR(30) NOT NULL,
	SEGUNDOAPELLIDO 		VARCHAR(30),
	FECHANAC				DATE NOT NULL,
	FOTO					VARCHAR(100) NOT NULL,
	CEDULAMAPFRE			VARCHAR(50) NOT NULL,
    SEXO					VARCHAR(7) NOT NULL,
	CONSTRAINT CH_SEXO CHECK (SEXO in('F','M')),
	CONSTRAINT PK_ESTUDIANTE PRIMARY KEY(CEDULAESCOLAR)
);

CREATE TABLE GRUPO(
	CODIGO 					VARCHAR(30),
	NOMBRE 					VARCHAR(30) NOT NULL,
	DESCRIPCION 			VARCHAR(30),
	CAPACIDAD 				INTEGER,
	PERIODO 				VARCHAR(50),
	CONSTRAINT PK_GRUPO PRIMARY KEY(CODIGO)
);

CREATE TABLE REP_EST(
	ID 						SERIAL,
	FK_CEDULA 				INTEGER NOT NULL,
	FK_CEDULAESCOLAR 		BIGINT NOT NULL,
	PARENTEZCO				VARCHAR(13) NOT NULL,
	CONSTRAINT CH_PARENTEZCO CHECK (PARENTEZCO in('Madre','Padre','Autorizado','Otro')),
	CONSTRAINT PK_REP_EST PRIMARY KEY(ID)
);

CREATE TABLE EMP_GRU_EST(
	ID 						SERIAL,
	FK_CEDULA 				INTEGER,
	FK_CEDULAESCOLAR 		BIGINT,
	FK_GRUPO 				VARCHAR(30) NOT NULL,
	CONSTRAINT PK_EMP_GRU_EST PRIMARY KEY(ID)
);

CREATE TABLE COMPROBANTE_PAGO(
	ID 						INTEGER,
	FK_EMPLEADO 			INTEGER,
	CONSTRAINT PK_COMPROBANTE_PAGO PRIMARY KEY(ID)
);

CREATE TABLE INASISTENCIA(
	ID						SERIAL,
	DIASFALTADOS			INTEGER NOT NULL,
	MES						VARCHAR(15) NOT NULL,
	ANO 					INTEGER NOT NULL,
	FK_EMPLEADO				INTEGER,
	CONSTRAINT PK_INASISTENCIA PRIMARY KEY(ID)
);

CREATE TABLE SUPLENCIA(
	ID						SERIAL,
	DIASADICIONALES			INTEGER NOT NULL,
	MES						VARCHAR(15) NOT NULL,
	ANO 					INTEGER NOT NULL,
	FK_EMPLEADO				INTEGER,
	CONSTRAINT PK_SUPLENCIA PRIMARY KEY(ID)
);

CREATE TABLE MENSUALIDAD_REPRESENTANTE(
	CODIGO				    VARCHAR(100) NOT NULL,
	FECHAPAGO			    DATE NOT NULL,
	DATOSPAGO				VARCHAR (100) NOT NULL,
	MONTO					INTEGER NOT NULL,
	BANCO					VARCHAR(30) NOT NULL,
	CODIGOTRANSFERENCIA    VARCHAR(50) NOT NULL,
	FK_REPRESENTANTE		INTEGER NOT NULL,
	FK_ESTUDIANTE			BIGINT NOT NULL,
	CONSTRAINT PK_MENSUALIDAD_REPRESENTANTE PRIMARY KEY(CODIGO)
);

insert into emp_gru_est values ((nextval('emp_gru_est_id_seq'), 16438861, null, '1A');