DROP DATABASE HenriPittier;

DROP TABLE REP_EST;
DROP TABLE EMP_GRU_EST;
DROP TABLE COMPROBANTE_PAGO;
DROP TABLE INASISTENCIA;
DROP TABLE SUPLENCIA;
DROP TABLE GRUPO;
DROP TABLE REPRESENTANTE;
DROP TABLE EMPLEADO;
DROP TABLE ESTUDIANTE;
DROP TABLE LUGAR;

DELETE TABLE REP_EST;
DELETE TABLE EMP_GRU_EST;
DELETE TABLE COMPROBANTE_PAGO;
DELETE TABLE INASISTENCIA;
DELETE TABLE SUPLENCIA;
DELETE TABLE GRUPO;
DELETE TABLE REPRESENTANTE;
DELETE TABLE EMPLEADO;
DELETE TABLE ESTUDIANTE;
DELETE TABLE LUGAR;