DROP DATABASE HenriPittier;

DROP TABLE REP_EST;
DROP TABLE EMP_GRU_EST;
DROP TABLE COMPROBANTE_PAGO;
DROP TABLE INASISTENCIA;
DROP TABLE SUPLENCIA;
DROP TABLE GRUPO;
DROP TABLE REPRESENTANTE;
DROP TABLE EMPLEADO;
DROP TABLE ESTUDIANTE;
DROP TABLE LUGAR;

DELETE FROM REP_EST;
DELETE FROM EMP_GRU_EST;
DELETE FROM COMPROBANTE_PAGO;
DELETE FROM INASISTENCIA;
DELETE FROM SUPLENCIA;
DELETE FROM GRUPO;
DELETE FROM REPRESENTANTE;
DELETE FROM EMPLEADO;
DELETE FROM ESTUDIANTE;
DELETE FROM LUGAR;