/***************************************MANEJO DE USUARIOS**************************************/
CREATE OR REPLACE FUNCTION EMPLEADO_INICIARSESION(varchar(50), varchar(15)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM EMPLEADO WHERE NOMBREUSUARIO = $1 AND CONTRASENA = $2) = 0) THEN

		RESULT := 204;
  	
  	ELSE
	
		RESULT := 200;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;


/****************************************CRUD EMPLEADO******************************************/
CREATE OR REPLACE FUNCTION EMPLEADO_REGISTRAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), varchar(20), integer, integer, integer, integer, date, date, varchar(11), varchar(11), varchar(30), integer, integer, varchar(100), varchar(50), varchar(15), varchar(80), varchar(80), varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 FK_LUGAR integer;

BEGIN
	IF ((SELECT COUNT(*) FROM EMPLEADO WHERE CEDULA = $1) = 0) THEN

		FK_LUGAR := (SELECT P.CODIGO FROM LUGAR m, LUGAR e, LUGAR p WHERE E.NOMBRE = $21 AND M.NOMBRE = $22 AND P.NOMBRE = $23 AND E.CODIGO = M.FK_LUGAR AND M.CODIGO = P.FK_LUGAR);
		INSERT INTO EMPLEADO (CEDULA, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, BANCO, SUELDOMENSUAL, SUELDOMENSUALEXTRA, SUELDOQUINCENAL, SUELDOQUINCENALEXTRA, FECHAINGRESO, FECHANAC, TELEFONOCASA, TELEFONOMOVIL, CARGO, ASISTENCIA, SUPLENCIA, FOTO, NOMBREUSUARIO, CONTRASENA, FK_LUGAR) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, FK_LUGAR);
		RESULT := 200;
  	
  	ELSE
	
		RESULT := 301;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION EMPLEADO_CONSULTAR_TODOS() RETURNS TABLE(CEDULA integer, PRIMERNOMBRE varchar(30), SEGUNDONOMBRE varchar(30), PRIMERAPELLIDO varchar(30), SEGUNDOAPELLIDO varchar(30), BANCO varchar(20), SUELDOMEN integer, SUELDOMENEXTRA integer, SUEDOQUIN integer, SUELDOQUINEXTRA integer, FECHAINGRESO date, FECHANAC date, TELFCASA varchar(11), TELFMOVIL varchar(11), CARGO varchar(30), ASISTENCIA integer, SUPLENCIA integer, FOTO varchar(100), USUARIO varchar(50), CLAVE varchar(15), ESTADO varchar(80), MUNICIPIO varchar(80), PARROQUIA varchar(80)) AS $$
DECLARE

BEGIN
	 RETURN QUERY
	 SELECT EM.CEDULA, EM.PRIMERNOMBRE, EM.SEGUNDONOMBRE, EM.PRIMERAPELLIDO, EM.SEGUNDOAPELLIDO, EM.BANCO, EM.SUELDOMENSUAL, EM.SUELDOMENSUALEXTRA, EM.SUELDOQUINCENAL, EM.SUELDOQUINCENALEXTRA, EM.FECHAINGRESO, EM.FECHANAC, EM.TELEFONOCASA, EM.TELEFONOMOVIL, EM.CARGO, EM.ASISTENCIA, EM.SUPLENCIA, EM.FOTO, EM.NOMBREUSUARIO, EM.CONTRASENA, E.NOMBRE, M.NOMBRE, P.NOMBRE
	 FROM EMPLEADO EM, LUGAR E, LUGAR M, LUGAR P
	 WHERE EM.FK_LUGAR = P.CODIGO AND P.FK_LUGAR = M.CODIGO AND M.FK_LUGAR = E.CODIGO
	 ;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION EMPLEADO_CONSULTAR_DETALLE(integer) RETURNS TABLE(CEDULA integer, PRIMERNOMBRE varchar(30), SEGUNDONOMBRE varchar(30), PRIMERAPELLIDO varchar(30), SEGUNDOAPELLIDO varchar(30), BANCO varchar(20), SUELDOMEN integer, SUELDOMENEXTRA integer, SUEDOQUIN integer, SUELDOQUINEXTRA integer, FECHAINGRESO date, FECHANAC date, TELFCASA varchar(11), TELFMOVIL varchar(11), CARGO varchar(30), ASISTENCIA integer, SUPLENCIA integer, FOTO varchar(100), USUARIO varchar(50), CLAVE varchar(15), ESTADO varchar(80), MUNICIPIO varchar(80), PARROQUIA varchar(80)) AS $$
DECLARE

BEGIN
	RETURN QUERY
	SELECT EM.CEDULA, EM.PRIMERNOMBRE, EM.SEGUNDONOMBRE, EM.PRIMERAPELLIDO, EM.SEGUNDOAPELLIDO, EM.BANCO, EM.SUELDOMENSUAL, EM.SUELDOMENSUALEXTRA, EM.SUELDOQUINCENAL, EM.SUELDOQUINCENALEXTRA, EM.FECHAINGRESO, EM.FECHANAC, EM.TELEFONOCASA, EM.TELEFONOMOVIL, EM.CARGO, EM.ASISTENCIA, EM.SUPLENCIA, EM.FOTO, EM.NOMBREUSUARIO, EM.CONTRASENA, E.NOMBRE, M.NOMBRE, P.NOMBRE
	FROM EMPLEADO EM, LUGAR E, LUGAR M, LUGAR P
	WHERE EM.FK_LUGAR = P.CODIGO AND P.FK_LUGAR = M.CODIGO AND M.FK_LUGAR = E.CODIGO AND EM.CEDULA = $1		
	 ;
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION EMPLEADO_MODIFICAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), varchar(20), integer, integer, integer, integer, date, date, varchar(11), varchar(11), varchar(30), integer, integer, varchar(100), varchar(50), varchar(15), varchar(80), varchar(80), varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 fk_lugar integer;

BEGIN
	IF ((SELECT COUNT(*) FROM EMPLEADO WHERE CEDULA = $1) = 1) THEN

		fk_lugar := (SELECT P.CODIGO FROM LUGAR m, LUGAR e, LUGAR p WHERE E.NOMBRE = $21 AND M.NOMBRE = $22 AND P.NOMBRE = $23 AND E.CODIGO = M.FK_LUGAR AND M.CODIGO = P.FK_LUGAR)
		UPDATE EMPLEADO SET CEDULA = $1, PRIMERNOMBRE = $2, SEGUNDONOMBRE = $3, PRIMERAPELLIDO = $4, SEGUNDOAPELLIDO = $5, BANCO = $6, SUELDOMENSUAL = $7, SUELDOMENSUALEXTRA = $8, SUELDOQUINCENAL = $9, SUELDOQUINCENALEXTRA = $10, FECHAINGRESO = $11, FECHANAC = $12, TELEFONOCASA = $13, TELEFONOMOVIL = $14, CARGO = $15, ASISTENCIA = $16, SUPLENCIA = $17, FOTO = $18, NOMBREUSUARIO = $19, CONTRASENA = $20, FK_LUGAR = fk_lugar WHERE CEDULA = $1;
		RESULT := 200;
  	
  	ELSE
	
		RESULT := 301;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION EMPLEADO_BORRAR(integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM EMPLEADO WHERE CEDULA = $1) = 1) THEN 

		DELETE FROM EMPLEADO WHERE CEDULA = $1;
		RESULT := 200;

	ELSE

		RESULT := 301;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;



