/*****************************CRUD REPRESENTANTE**********************************/

CREATE OR REPLACE FUNCTION REPRESENTANTE_REGISTRAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), date, varchar(11), varchar(11), varchar(17), varchar(100), varchar(80), varchar(80), varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 FK_LUGAR integer;

BEGIN
	IF ((SELECT COUNT(*) FROM REPRESENTANTE WHERE CEDULA = $1) = 0) THEN

		FK_LUGAR := (SELECT p.CODIGO FROM LUGAR m, LUGAR e, LUGAR p WHERE e.NOMBRE = $11 AND m.NOMBRE = $12 AND p.NOMBRE = $13 AND e.CODIGO = m.FK_LUGAR AND m.CODIGO = p.FK_LUGAR)
		INSERT INTO REPRESENTANTE (CEDULA, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, FECHANAC, TELEFONOCASA, TELEFONOMOVIL, TIPO, FOTO, FK_LUGAR) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, FK_LUGAR);
		RESULT := 200;
  	
  	ELSE
	
		RESULT := 301;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION REPRESENTANTE_MODIFICAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), date, varchar(11), varchar(11), varchar(17), varchar(100), varchar(80), varchar(80), varchar(80)) RETURNS integer AS $$
DECLARE
 RESULT integer;
 fk_lugar integer;

BEGIN
	IF ((SELECT COUNT(*) FROM REPRESENTANTE WHERE CEDULA = $1) = 0) THEN

		fk_lugar := (SELECT p.CODIGO FROM LUGAR m, LUGAR e, LUGAR p WHERE e.NOMBRE = $11 AND m.NOMBRE = $12 AND p.NOMBRE = $13 AND e.CODIGO = m.FK_LUGAR AND m.CODIGO = p.FK_LUGAR)
		UPDATE REPRESENTANTE SET (CEDULA = $1, PRIMERNOMBRE = $2, SEGUNDONOMBRE = $3, PRIMERAPELLIDO = $4, SEGUNDOAPELLIDO = $5, FECHANAC = $6, TELEFONOCASA = $7, TELEFONOMOVIL = $8, TIPO = $9, FOTO = $10, FK_LUGAR = fk_lugar ) WHERE CEDULA = $1;
		RESULT := 200;
  	
  	ELSE
	
		RESULT := 301;
	
	END IF;
 	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION REPRESENTANTE_BORRAR(integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM REPRESENTANTE WHERE CEDULA = $1) = 0) THEN 

		DELETE FROM REPRESENTANTE WHERE CEDULA = $1;
		RESULT := 200;

	ELSE

		RESULT := 301;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;


/*****************************CRUD ESTUDIANTE**********************************/
CREATE OR REPLACE FUNCTION ESTUDIANTE_REGISTRAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), date, varchar(100)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM ESTUDIANTE WHERE CEDULAESCOLAR = $1) = 0) THEN 

		INSERT INTO ESTUDIANTE (CEDULAESCOLAR, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, FECHANAC, FOTO);
		RESULT := 200;

	ELSE

		RESULT := 301;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION ESTUDIANTE_MODIFICAR(integer, varchar(30), varchar(30), varchar(30), varchar(30), date, varchar(100)) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM ESTUDIANTE WHERE CEDULAESCOLAR = $1) = 0) THEN 

		UPDATE ESTUDIANTE SET (CEDULAESCOLAR = $1, PRIMERNOMBRE = $2, SEGUNDONOMBRE = $3, PRIMERAPELLIDO = $4, SEGUNDOAPELLIDO = $5, FECHANAC = $6, FOTO = $7) WHERE CEDULAESCOLAR = $1;
		RESULT := 200;

	ELSE

		RESULT := 301;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION ESTUDIANTE_BORRAR(integer) RETURNS integer AS $$
DECLARE
 RESULT integer;

BEGIN
	IF ((SELECT COUNT(*) FROM ESTUDIANTE WHERE CEDULAESCOLAR = $1) = 0) THEN 

		DELETE FROM ESTUDIANTE WHERE CEDULAESCOLAR = $1;
		RESULT := 200;

	ELSE

		RESULT := 301;

	END IF;
	RETURN RESULT;
END;
$$ LANGUAGE plpgsql;
